name: login_flow
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_lints: ^3.0.0
  blurry_modal_progress_hud: ^1.1.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  firebase_core: ^2.27.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.8
  quickalert: ^1.1.0
  provider: ^6.1.2
  firebase_database: ^10.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/ui_icons/
